In [35]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import scipy
import sklearn
import random
import operator
#from src import functions

In [56]:
df = pd.DataFrame({"A": [1, 2, 3, 4, 5], "B": [4, 5, 6, 7, 8], "Churn": [1, 1, 0, 1, 0]})
x = np.random.rand(5,2)

In [57]:
y = np.array([0, 1, 0, 0, 1])

In [58]:
new_table = np.c_[df,y]

#new_table = pd.DataFrame(new_table, row = ['Taille', 'poids', 'couleur', 'sexe', 'Churn'])

In [62]:
print(df)
print(new_table)

   A  B  Churn
0  1  4      1
1  2  5      1
2  3  6      0
3  4  7      1
4  5  8      0
[[1 4 1 0]
 [2 5 1 1]
 [3 6 0 0]
 [4 7 1 0]
 [5 8 0 1]]


In [60]:
data_loyal = new_table[new_table['Churn'] == 'No'].reset_index()
data_churn = new_table[new_table['Churn'] == 'Yes'].reset_index()

IndexError: only integers, slices (`:`), ellipsis (`...`), numpy.newaxis (`None`) and integer or boolean arrays are valid indices

In [100]:
np.random.shuffle(new_table)
#np.random.shuffle(data_loyal)
#np.random.shuffle(data_churn)

In [100]:
#data_loyal.sort_values(by='churn', ascending=0)
#data_churn.sort_values(by='churn', ascending=0)

In [101]:
Per_test = 80
#je n'arrive pas a mettre comme parametre les dimensions des tableaux

In [99]:
#crée les matrices train et test
x_test = new_table[3:,1:]
y_test = new_table[3:,3:]

x_train = new_table[2:,1:]
y_train = new_table[2:,3:]



In [ ]:
#np.random.shuffle(x_test)
#np.random.shuffle(y_test)

In [ ]:
#np.random.shuffle(x_train)
#np.random.shuffle(y_train)